# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2017 Microchip Corporation
#                    Wenyou Yang <wenyou.yang@microchip.com>
# Copyright (C) 2023 Innovative Electronics, LLC
#                    Sam Birch <sbirch@innovative-electronics.com>

obj-y += kent_gfxdemo.o
obj-$(CONFIG_I2C_EEPROM) += ../../atmel/common/mac_eeprom.o
