# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2017 Microchip Corporation
#                    Wenyou Yang <wenyou.yang@microchip.com>
# Copyright (C) 2023 Kent Scientific Corporation
#                    Sam Birch <sam@profirmserv.com>

obj-y += kent_gfxdemo.o
obj-$(CONFIG_I2C_EEPROM) += ../../atmel/common/mac_eeprom.o
